name: bills_calculator
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutterfire_cli: ^1.0.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
